---
output:
  md_document:
    variant: markdown_github
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "NEWS-"
)
```

# Updates (Version 1.6.1)
## Function Updates
Added the od.2m.mod function for identifying the jointly optimal allocation for main and moderation effects in multisite randomized trials with binary and continuous moderators at level 1 or level 2. 

Deleted the od.2m.111m function as it is now a part of the od.2m.mod function.

Added the od.2m.only.mod function for identifying optimal allocation for 
moderation effects in two-level multisite randomized trials.

Added the power.2m.mod function for power analysis for 
moderation effects in two-level multisite randomized trials.

Added the plot.power function to plot power curves.

# Updates (Version 1.5.0)
## Function Updates
Added od functions to identify the jointly optimal allocation for various
experiments investigating main and moderation effects.

## New Features
Changed the optimization method from first-order derivative to ant colony 
optimization for od.2m and od.3m functions for more precise optimization 
identification.

# Updates (Version 1.4.4)
## New Features
Fixed bugs to allow extreme correlations to be in range of [-1, 1] and other
bugs in function arguments.


# Updates (Version 1.4.2)
## New Features
Updated the package description/title and updated arguments and solutions for the function of power.1.111.


# Updates (Version 1.4.1)
## New Features
Added functions od.1.111 and power.1.111, for optimal design and statistical power of single-level randomized controlled trials probing mediation effects under the Sobel test and the joint significance test.

# Updates (Version 1.3.1)
## New Features
- Fixed some bugs, this version allows ICCs and R-squared to be 0 or 1.



# Updates (Version 1.2.1)
## New Features
- Added functions od.2.221 and power.2.221, for optimal design and statistical power of two-level cluster-randomized trials (CRTs) probing mediation effects with cluster-level mediators under the Sobel test and joint significance test across different optimization methods (partial derivative, ant colony optimization).

# Updates (Version 1.0.2)
- update references
- update documentation for these functions

# Updates (Version 1.0.0)
- Added functions (od.1 and power.1) for individual randomized controlled trials 
- Added functions (od.2m and power.2m) for two-level multisite randomized trials 
- Added functions (od.3m and power.3m) for three-level multisite randomized trials 
- Added functions (od.4m and power.4m) for four-level multisite randomized trials 
- Updated function 're' to include all the seven types of trials

# Updates (Version 0.7.3)
- Added function 're' to calculate relative efficiency of two studies
- Added functions (od.3 and power.3) for three-level cluster randomized trials 
- Added functions (od.4 and power.4) for four-level cluster randomized trials 
- Changed license from GPL-2 to GPL-3
- Added variance of treatment effect to output in 'od' functions
- Added required sample size to the output in required budget calculation in 'power' functions 

# Initial Release of odr (Version 0.3.2)
- Optimal design and statistical power for two-level group randomized trials.
